import gradio as gr
from styles import ADVANCED_STYLE

with gr.Blocks(css=ADVANCED_STYLE, theme='gradio/soft') as demo:
  with gr.Column(elem_id="col-container"):
    gr.Markdown(
        "# Marking preference of responses generated by SFT model",
        elem_id="top-title"
    )
    gr.Markdown(
        "The recorded preferences will be used to train a reward model for the RLHF"
    )

    prompt = gr.Textbox(
        label="", elem_id="prompt-txt-input", placeholder="Enter an instruction"
      )

    with gr.Row(elem_id="middle"):
      gr.Chatbot(
          [
              ("user input 1...", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lobortis rutrum aliquet. Vivamus sagittis consequat justo, vitae convallis tortor lobortis sed. Sed congue dui id ipsum euismod, ac vulputate ligula convallis. Maecenas imperdiet nec ante id pretium. Morbi imperdiet fringilla justo. Vestibulum id lobortis tellus, vel efficitur odio. Sed ultricies elit sit amet efficitur egestas. Aliquam pulvinar, massa at porttitor volutpat, leo ex hendrerit velit, non vehicula ligula sapien ac nisi."),
              ("user input 2...", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lobortis rutrum aliquet. Vivamus sagittis consequat justo, vitae convallis tortor lobortis sed. Sed congue dui id ipsum euismod, ac vulputate ligula convallis. Maecenas imperdiet nec ante id pretium. Morbi imperdiet fringilla justo. Vestibulum id lobortis tellus, vel efficitur odio. Sed ultricies elit sit amet efficitur egestas. Aliquam pulvinar, massa at porttitor volutpat, leo ex hendrerit velit, non vehicula ligula sapien ac nisi.")           
          ],
          label="Chat History",
          elem_id="chatbot",
          visible=False
      )
      
      with gr.Column(elem_id="middle-right"):
        gr.Markdown("### Choose the most helpful and honest response from the current turn of conversation", elem_id="middle-title")

        gr.Textbox(
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lobortis rutrum aliquet. Vivamus sagittis consequat justo, vitae convallis tortor lobortis sed. Sed congue dui id ipsum euismod, ac vulputate ligula convallis. Maecenas imperdiet nec ante id pretium. Morbi imperdiet fringilla justo. Vestibulum id lobortis tellus, vel efficitur odio. Sed ultricies elit sit amet efficitur egestas. Aliquam pulvinar, massa at porttitor volutpat, leo ex hendrerit velit, non vehicula ligula sapien ac nisi.",
            lines=15,
            label="A"
        )
        gr.Textbox(
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lobortis rutrum aliquet. Vivamus sagittis consequat justo, vitae convallis tortor lobortis sed. Sed congue dui id ipsum euismod, ac vulputate ligula convallis. Maecenas imperdiet nec ante id pretium. Morbi imperdiet fringilla justo. Vestibulum id lobortis tellus, vel efficitur odio. Sed ultricies elit sit amet efficitur egestas. Aliquam pulvinar, massa at porttitor volutpat, leo ex hendrerit velit, non vehicula ligula sapien ac nisi.",
            lines=15,
            label="B"
        )

        with gr.Row(elem_id="middle-right-bottom"):
          gr.Button("A", elem_id="res-pref-first-btn")
          gr.Button("A", elem_id="res-pref-second-btn")
          gr.Button("A", elem_id="res-pref-third-btn")
          gr.Button("A", elem_id="res-pref-fourth-btn")
          gr.Button("B", elem_id="res-pref-fifth-btn")
          gr.Button("B", elem_id="res-pref-sixth-btn")
          gr.Button("B", elem_id="res-pref-seventh-btn")
          gr.Button("B", elem_id="res-pref-eighth-btn")

    with gr.Column(elem_id="bottom", visible=False):
      gr.Markdown("## Choose the overall score when exiting", elem_id="bottom-title")

      with gr.Row(elem_id="bottom-bottom"):
        gr.Button("1", elem_id="chat-pref-first-btn")
        gr.Button("2", elem_id="chat-pref-second-btn")
        gr.Button("3", elem_id="chat-pref-third-btn")
        gr.Button("4", elem_id="chat-pref-fourth-btn")
        gr.Button("5", elem_id="chat-pref-fifth-btn")
        gr.Button("6", elem_id="chat-pref-sixth-btn")
        gr.Button("7", elem_id="chat-pref-seventh-btn")
        gr.Button("8", elem_id="chat-pref-eighth-btn")
        gr.Button("9", elem_id="chat-pref-nineth-btn")
        gr.Button("10", elem_id="chat-pref-tenth-btn")

demo.queue().launch()